name: 'branch-number'
description: 'Export branch name number as environment variable.'
author: 'dannevesdantas'
branding:
  color: git-branch
  icon: blue
inputs:
  branch-name:
    description: 'Branch name without the refs/heads/ part. For example release/3.2.0'
    required: true
  delimiter:
    description: 'Delimiter that separate the branch name part from the branch name number part. For example / or - Default value is /'
    required: false
    default: '/'

runs:
  using: 'composite'
  steps:
    - run: |
        chcp 65001 #set code page to utf-8
        echo ("BRANCH_NUMBER=" + "${{ inputs.branch-name }}".Split("${{ inputs.delimiter }}")[-1]) >> $env:GITHUB_ENV
      shell: powershell
      
